spring:
  application:
    name: antiprocrostinate
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: create
  datasource:
    url: jdbc:postgresql://${DB_HOST}:${DB_PORT}/${DB_NAME}
    username: ${DB_USER}
    password: ${DB_PASSWORD}
    driverClassName: org.postgresql.Driver
  sql:
    init:
      platform: postgres

jwt:
  secret: "secret"
  expiration: 1800000

